version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app # sync current directory with container
      - /app/node_modules # won't touch node modules as we are creating another anonymus volume for it
    environment:
      - NODE_ENV=development
    command: npm run dev
